### ISSUE TITLE
update the compatibility on Openmodelica platform

### ISSUE THREAD

**Issue by Satinelamp** [modelica-3rdparty/Modelica_DeviceDrivers#338]
On the main page of MDD, the compatibility on OpenModelica(OM) is about OM 1.10.0, but the current release of OM is 1.17.0, I didn't find the coverage information of MDD on [OpenModelica coverage test page](https://trac.openmodelica.org/OpenModelica/wiki/CoverageIssues), but based on #319, MDD works on OM 1.16.0, so why not update the information. 
![1](https://user-images.githubusercontent.com/62006565/114427396-a2740900-9bed-11eb-9b7b-b9e231ed6251.png)
![2](https://user-images.githubusercontent.com/62006565/114427401-a3a53600-9bed-11eb-9f0d-ba4d654fbadd.png)
![Snipaste_2021-04-13_00-10-08](https://user-images.githubusercontent.com/62006565/114427405-a43dcc80-9bed-11eb-8bb6-b2768929463e.png)

**Comment by bernhard-thiele** [comment]
Hm, the present text identifies the first OM release known to partially work with MDD. Since that OM release is some time ago one could also simply write that OM partially supports the library. However, I'm not in favor in listing all releases since v1.11.0 Beta 1, I also usually don't systematically test with new OM releases. Such tests would be nice, but somebody would need to do them or write a CI testing code which automatizes such tests.
